# Generated by Django 5.2.11 on 2026-02-28 20:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('lsst_diaObject_diaObjectId', models.TextField(unique=True)),
                ('lsst_diaSource_diaSourceId', models.TextField(null=True)),
                ('ra_deg', models.FloatField()),
                ('dec_deg', models.FloatField()),
                ('event_time', models.DateTimeField()),
                ('ingest_time', models.DateTimeField(auto_now_add=True)),
                ('schema_version', models.IntegerField(default=1)),
                ('payload', models.JSONField()),
                ('status', models.TextField(choices=[('INGESTED', 'ingested'), ('QUEUED', 'queued'), ('MATCHED', 'matched'), ('NOTIFIED', 'notified')], default='INGESTED')),
            ],
        ),
    ]
