# Generated by Django 6.0.5 on 2026-08-14 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_notif_sent_at_index_concurrent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TnsSnapshotMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_refresh_epoch', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tns_snapshot_meta',
            },
        ),
        migrations.CreateModel(
            name='TnsAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.BooleanField(default=False)),
                ('snapshot_epoch', models.DateTimeField(null=True)),
                ('objid', models.BigIntegerField(null=True)),
                ('name', models.TextField(null=True)),
                ('name_prefix', models.TextField(null=True)),
                ('type', models.TextField(null=True)),
                ('redshift', models.FloatField(null=True)),
                ('separation_arcsec', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert', models.OneToOneField(db_column='lsst_diaobject_diaobjectid', on_delete=django.db.models.deletion.CASCADE, to='core.alert', to_field='lsst_diaObject_diaObjectId')),
            ],
            options={
                'db_table': 'tns_associations',
            },
        ),
        migrations.CreateModel(
            name='TnsObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objid', models.BigIntegerField(unique=True)),
                ('name', models.TextField()),
                ('name_prefix', models.TextField(null=True)),
                ('ra_deg', models.FloatField()),
                ('dec_deg', models.FloatField()),
                ('type', models.TextField(null=True)),
                ('redshift', models.FloatField(null=True)),
                ('healpix_ipix', models.BigIntegerField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tns_objects',
                'indexes': [models.Index(fields=['healpix_ipix'], name='core_tns_healpix_ipix_idx')],
            },
        ),
    ]
