# Generated by Django 6.0.5 on 2026-09-28 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_tnssnapshotmeta_tnsassociation_tnsobject'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvenanceSet',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content_hash', models.TextField(unique=True)),
                ('crossmatch_radius_arcsec', models.FloatField(null=True)),
                ('catalogs', models.JSONField()),
                ('reliability_cuts', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'provenance_sets',
            },
        ),
        migrations.CreateModel(
            name='ObjectCrossmatchRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('match_version', models.IntegerField(default=1)),
                ('catalog_outcomes', models.JSONField()),
                ('brokers', models.JSONField()),
                ('crossmatched_at', models.DateTimeField()),
                ('alert', models.ForeignKey(db_column='lsst_diaobject_diaobjectid', on_delete=django.db.models.deletion.CASCADE, to='core.alert', to_field='lsst_diaObject_diaObjectId')),
                ('provenance_set', models.ForeignKey(db_column='provenance_set_id', on_delete=django.db.models.deletion.PROTECT, to='core.provenanceset')),
            ],
            options={
                'db_table': 'object_crossmatch_records',
                'constraints': [models.UniqueConstraint(fields=('alert', 'match_version'), name='unique_object_crossmatch_record')],
            },
        ),
    ]
