name: crossmatch

networks:
  internal:
    external: false

volumes:
  django-db: {}
  django-static: {}
  valkey-data: {}

services:
  alert-consumer:
    image: hub.ncsa.illinois.edu/crossmatch-service/alert-consumer:dev
    platform: linux/x86_64
    networks:
      - internal
    build:
      context: ../crossmatch
      dockerfile: ../docker/Dockerfile
      args:
        UID: "${USERID:-1000}"
    command: bash entrypoints/run_alert_consumer.sh
    environment:
      # Dev environment settings
      MAKE_MIGRATIONS: "${MAKE_MIGRATIONS:-false}"
      DJANGO_DEBUG: "${DJANGO_DEBUG:-true}"
      LOG_LEVEL: ${LOG_LEVEL:-DEBUG}
      DEV_MODE: "${DEV_MODE:-true}" # Enable Django dev server instead of uvicorn
      # Django base configuration
      DJANGO_SUPERUSER_PASSWORD: "${DJANGO_SUPERUSER_PASSWORD:-password}"
      DJANGO_SUPERUSER_USERNAME: "${DJANGO_SUPERUSER_USERNAME:-admin}"
      DJANGO_SUPERUSER_EMAIL: "${DJANGO_SUPERUSER_EMAIL:-test@example.com}"
      # Django database configuration
      DATABASE_HOST: "${DATABASE_HOST:-django-db}"
      DATABASE_PORT: "${DATABASE_PORT:-5432}"
      DATABASE_DB: "${DATABASE_DB:-django}"
      DATABASE_USER: "${DATABASE_USER:-django}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD:-password}"
      # Message broker configuration
      VALKEY_SERVICE: "${VALKEY_SERVICE:-redis}"
      VALKEY_PORT: "${VALKEY_PORT:-6379}"
      # Application configuration
      APP_ROOT_DIR: "${APP_ROOT_DIR:-/opt}"
      # TODO: Increase interval when running real task
      QUERY_HEROIC_INTERVAL: "${QUERY_HEROIC_INTERVAL:-15}"
    volumes:
      - "django-static:${APP_ROOT_DIR:-/opt}/static"
      - ../crossmatch:/opt/crossmatch

  celery-worker:
    image: hub.ncsa.illinois.edu/crossmatch-service/celery:dev
    platform: linux/x86_64
    build:
      context: ../crossmatch
      dockerfile: ../docker/Dockerfile
      args:
        UID: "${USERID:-1000}"
    command: bash entrypoints/run_celery_worker.sh alerts
    restart: on-failure
    depends_on:
      valkey:
        condition: service_healthy
    networks:
      - internal
    deploy:
      mode: replicated
      replicas: 2
      resources:
        reservations:
          cpus: '0.25'
          memory: 1G
        limits:
          cpus: "${CELERY_WORKER_LIMIT_CPUS:-4.0}"
          memory: ${CELERY_WORKER_LIMIT_MEMORY:-4G}
    environment:
      # Dev environment settings
      DJANGO_DEBUG: "${DJANGO_DEBUG:-true}"
      DEV_MODE: "${DEV_MODE:-true}" # Enable Django dev server instead of uvicorn
      CELERY_LOG_LEVEL: ${CELERY_LOG_LEVEL:-INFO}
      CELERY_CONCURRENCY: ${CELERY_CONCURRENCY:-4}
      # Django database configuration
      DATABASE_HOST: "${DATABASE_HOST:-django-db}"
      DATABASE_PORT: "${DATABASE_PORT:-5432}"
      DATABASE_DB: "${DATABASE_DB:-django}"
      DATABASE_USER: "${DATABASE_USER:-django}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD:-password}"
      # Message broker configuration
      VALKEY_SERVICE: "${VALKEY_SERVICE:-redis}"
      VALKEY_PORT: "${VALKEY_PORT:-6379}"
      # Application configuration
      APP_ROOT_DIR: "${APP_ROOT_DIR:-/opt}"
    volumes:
      - ../crossmatch:/opt/crossmatch

  celery-beat:
    restart: on-failure
    depends_on:
      valkey:
        condition: service_healthy
    image: hub.ncsa.illinois.edu/crossmatch-service/celery:dev
    build:
      context: ../crossmatch
      dockerfile: ../docker/Dockerfile
      args:
        UID: "${USERID:-1000}"
    command: bash entrypoints/run_celery_beat.sh
    environment:
      DJANGO_DEBUG: "${DJANGO_DEBUG:-true}"
      DEV_MODE: "${DEV_MODE:-true}" # Enable Django dev server instead of uvicorn
      CELERY_LOG_LEVEL: ${CELERY_LOG_LEVEL:-INFO}
      # Django database configuration
      DATABASE_HOST: "${DATABASE_HOST:-django-db}"
      DATABASE_PORT: "${DATABASE_PORT:-5432}"
      DATABASE_DB: "${DATABASE_DB:-django}"
      DATABASE_USER: "${DATABASE_USER:-django}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD:-password}"
      # Message broker configuration
      VALKEY_SERVICE: "${VALKEY_SERVICE:-redis}"
      VALKEY_PORT: "${VALKEY_PORT:-6379}"
      # QUERY_HEROIC_INTERVAL
      # TODO: Increase interval when running real task
      QUERY_HEROIC_INTERVAL: "${QUERY_HEROIC_INTERVAL:-15}"
    networks:
      - internal
    volumes:
      - ../crossmatch:/opt/crossmatch

  flower:
    image: hub.ncsa.illinois.edu/crossmatch-service/celery:dev
    platform: linux/x86_64
    build:
      context: ../crossmatch
      dockerfile: ../docker/Dockerfile
      args:
        UID: "${USERID:-1000}"
    command: bash entrypoints/run_flower.sh
    networks:
      internal:
        aliases:
          - ${FLOWER_HOST:-flower}
    ports:
      - 127.0.0.1:${FLOWER_PORT:-8888}:${FLOWER_PORT:-8888}
    environment:
      # Message broker configuration
      VALKEY_SERVICE: "${VALKEY_SERVICE:-redis}"
      VALKEY_PORT: "${VALKEY_PORT:-6379}"
      # Flower configuration
      FLOWER_LOG_LEVEL: "${FLOWER_LOG_LEVEL:-INFO}"
      FLOWER_URL_PREFIX: "${FLOWER_URL_PREFIX:-}"
      FLOWER_HOST: "${FLOWER_HOST:-flower}"
      FLOWER_PORT: "${FLOWER_PORT:-8888}"
      # Django database configuration
      DATABASE_HOST: "${DATABASE_HOST:-django-db}"
      DATABASE_PORT: "${DATABASE_PORT:-5432}"
      DATABASE_DB: "${DATABASE_DB:-django}"
      DATABASE_USER: "${DATABASE_USER:-django}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD:-password}"

  django-db:
    image: postgres:18.3
    platform: linux/x86_64
    restart: always
    networks:
      internal:
        aliases:
          - ${DATABASE_HOST:-django-db}
    environment:
      POSTGRES_USER: "${DATABASE_USER:-django}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD:-password}"
      POSTGRES_DB: "${DATABASE_DB:-django}"
    volumes:
      - django-db:/var/lib/postgresql

  valkey:
    image: valkey/valkey:9.0.3
    command: [ "valkey-server", "/usr/local/etc/valkey/valkey.conf" ]
    ports:
      - 127.0.0.1:${VALKEY_PORT:-6379}:6379
    networks:
      internal:
        aliases:
          - "${VALKEY_SERVICE:-redis}"
    volumes:
      - valkey-data:/data
      - ./valkey:/usr/local/etc/valkey:ro
    healthcheck:
      test: [ "CMD-SHELL", "valkey-cli -p ${VALKEY_PORT:-6379} ping | grep PONG"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_interval: 5s
      start_period: 5s
