apiVersion: v2
name: crossmatch-service
description: This service consumes the Vera Rubin Observatory transient alert stream, crossmatches the coordinates against public source catalogs, and publishes the results as a derivative alert stream for the astrophysical community.
type: application
version: 1.0.0
dependencies:
- name: redis
  version: "2.1.x"
  repository: https://groundhog2k.github.io/helm-charts/
  condition: redis.enabled
