{{- if .Values.database.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.database.clusterName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.database.clusterName }}
  template:
    metadata:
      labels:
        app: {{ .Values.database.clusterName }}
    spec:
      containers:
      - name: postgres
        image: postgres:{{ .Values.database.imageTag | default "18.3" }}
        ports:
        - containerPort: {{ .Values.database.port }}
        env:
        - name: POSTGRES_DB
          value: {{ .Values.database.initdb.database | quote }}
        - name: POSTGRES_USER
          value: {{ .Values.database.initdb.username | quote }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: {{ .Values.database.initdb.existingSecret | quote }}
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql
      volumes:
      - name: postgres-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.clusterName }}
spec:
  selector:
    app: {{ .Values.database.clusterName }}
  ports:
  - port: {{ .Values.database.port }}
    targetPort: {{ .Values.database.port }}
{{- end }}
