{{- if .Values.antares_consumer.enabled }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.antares_consumer.service.host | quote }}
  {{- with .Values.common.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.antares_consumer.replicaCount }}
  serviceName: {{ .Values.antares_consumer.service.host | quote }}
  selector:
    matchLabels:
      app: {{ .Values.antares_consumer.service.host | quote }}
  template:
    metadata:
      labels:
        app: {{ .Values.antares_consumer.service.host | quote }}
        app.kubernetes.io/component: alert-consumer
    spec:
      containers:
      - name: alert-consumer
        image: {{ .Values.common.image.repo }}:{{ .Values.common.image.tag }}
        imagePullPolicy: {{ .Values.common.image.imagePullPolicy }}
        command:
        - /bin/bash
        - -c
        - bash entrypoints/run_antares_ingest.sh
        env:
          {{- include "common.env" . | nindent 10 }}
          {{- include "django.env" . | nindent 10 }}
          {{- include "db.env" . | nindent 10 }}
          {{- include "valkey.env" . | nindent 10 }}
          {{- include "celery.env" . | nindent 10 }}
          {{- include "antares.env" . | nindent 10 }}
        {{- with  .Values.antares_consumer.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: celery-worker
  {{- with .Values.common.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.celery.workers.replicaCount }}
  serviceName: celery-worker
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
        app.kubernetes.io/component: celery-worker
        app.kubernetes.io/name: celery-worker
    spec:
      containers:
      - name: worker
        image: {{ .Values.common.image.repo }}:{{ .Values.common.image.tag }}
        imagePullPolicy: {{ .Values.common.image.imagePullPolicy }}
        command:
        - /bin/bash
        - -c
        - bash entrypoints/run_celery_worker.sh alerts
        env:
          - name: CELERY_CONCURRENCY
            value: {{ .Values.celery.workers.concurrency | quote }}
          - name: CELERY_LOG_LEVEL
            value: {{ .Values.celery.log_level | quote }}
          {{- include "common.env" . | nindent 10 }}
          {{- include "db.env" . | nindent 10 }}
          {{- include "valkey.env" . | nindent 10 }}
          {{- include "celery.env" . | nindent 10 }}
          {{- include "hopskotch.env" . | nindent 10 }}
          {{- include "crossmatch.env" . | nindent 10 }}
        {{- with  .Values.celery.workers.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        # References for probes:
        #   - https://github.com/celery/celery/issues/4079
        #   - https://medium.com/ambient-innovation/health-checks-for-celery-in-kubernetes-cf3274a3e106
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - test $(($(date +%s) - $(stat -c %Y /tmp/worker_heartbeat))) -lt 10
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - test -e /tmp/worker_ready
          initialDelaySeconds: 10
          periodSeconds: 5

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: celery-beat
  {{- with .Values.common.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.celery.beat.replicaCount }}
  serviceName: celery-beat
  selector:
    matchLabels:
      app: celery-beat
  template:
    metadata:
      labels:
        app: celery-beat
    spec:
      containers:
      - name: beat
        image: {{ .Values.common.image.repo }}:{{ .Values.common.image.tag }}
        imagePullPolicy: {{ .Values.common.image.imagePullPolicy }}
        command:
        - /bin/bash
        - -c
        - bash entrypoints/run_celery_beat.sh
        env:
          {{- include "common.env" . | nindent 10 }}
          {{- include "db.env" . | nindent 10 }}
          {{- include "valkey.env" . | nindent 10 }}
          {{- include "crossmatch.env" . | nindent 10 }}
{{- end }}

{{- if .Values.lasair_consumer.enabled }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.lasair_consumer.service.host | quote }}
  {{- with .Values.common.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.lasair_consumer.replicaCount }}
  serviceName: {{ .Values.lasair_consumer.service.host | quote }}
  selector:
    matchLabels:
      app: {{ .Values.lasair_consumer.service.host | quote }}
  template:
    metadata:
      labels:
        app: {{ .Values.lasair_consumer.service.host | quote }}
        app.kubernetes.io/component: lasair-consumer
    spec:
      containers:
      - name: lasair-consumer
        image: {{ .Values.common.image.repo }}:{{ .Values.common.image.tag }}
        imagePullPolicy: {{ .Values.common.image.imagePullPolicy }}
        command:
        - /bin/bash
        - -c
        - bash entrypoints/run_lasair_ingest.sh
        env:
          {{- include "common.env" . | nindent 10 }}
          {{- include "django.env" . | nindent 10 }}
          {{- include "db.env" . | nindent 10 }}
          {{- include "valkey.env" . | nindent 10 }}
          {{- include "celery.env" . | nindent 10 }}
          - name: LASAIR_KAFKA_SERVER
            value: {{ .Values.lasair_consumer.kafka_server | quote }}
          - name: LASAIR_TOPIC
            value: {{ .Values.lasair_consumer.topic | quote }}
          - name: LASAIR_GROUP_ID
            value: {{ .Values.lasair_consumer.group_id | quote }}
        {{- with .Values.lasair_consumer.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
{{- end }}

{{- if .Values.pittgoogle_consumer.enabled }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.pittgoogle_consumer.service.host | quote }}
  {{- with .Values.common.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.pittgoogle_consumer.replicaCount }}
  serviceName: {{ .Values.pittgoogle_consumer.service.host | quote }}
  selector:
    matchLabels:
      app: {{ .Values.pittgoogle_consumer.service.host | quote }}
  template:
    metadata:
      labels:
        app: {{ .Values.pittgoogle_consumer.service.host | quote }}
        app.kubernetes.io/component: pittgoogle-consumer
    spec:
      containers:
      - name: pittgoogle-consumer
        image: {{ .Values.common.image.repo }}:{{ .Values.common.image.tag }}
        imagePullPolicy: {{ .Values.common.image.imagePullPolicy }}
        command:
        - /bin/bash
        - -c
        - bash entrypoints/run_pittgoogle_ingest.sh
        env:
          {{- include "common.env" . | nindent 10 }}
          {{- include "django.env" . | nindent 10 }}
          {{- include "db.env" . | nindent 10 }}
          {{- include "valkey.env" . | nindent 10 }}
          {{- include "celery.env" . | nindent 10 }}
          {{- include "pittgoogle.env" . | nindent 10 }}
        volumeMounts:
        - name: gcp-key
          mountPath: /var/run/secrets/gcp
          readOnly: true
        {{- with .Values.pittgoogle_consumer.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      volumes:
      - name: gcp-key
        secret:
          secretName: gcp-pittgoogle
          items:
          - key: key.json
            path: key.json
{{- end }}
